### PR TITLE
Update meilisearch-js dependency verison (v0.44)

### PR DESCRIPTION
**Pull request by curquiza**
- update `meilisearch` js client
- update `parcel` and `turbo`
- get rid of angular playground tests, as [angular-instantsearch got deprecated](https://www.algolia.com/blog/algolia/migrating-from-angular-instantsearch/)

### CODE REVIEW

**Comment by curquiza** [comment]
@flevi29 sorry I don't have that much time, but I can spend more time next week. If you have time in the meantime, can you help me upgrade the version of meilisearch-js correctly in instant-meilisearch, please? 😊

**Comment by flevi29** [comment]
@curquiza I'll do it tomorrow.

**Comment by flevi29** [comment]
Okay, now it passes, I'm going to add changeset and description a little later.

**Review by flevi29 — APPROVED** [review]
I think now it's good to go.

**Review by flevi29 — DISMISSED** [review]
Okay, now it LGTM for real.

**Review by flevi29 — APPROVED** [review]

**Comment by curquiza** [comment]
Thank you very much @flevi29 ❤️

bors merge

**Pull request merged**
