### PR TITLE
🐛 fix: Don't overwrite object ID in geosearch response

### LINKED ISSUE #1308: `instant-meilisearch` geosearch overwrites `objectID`
**Description**
I have an index I am using geosearch on, using `instant-meilisearch` + `react-instantsearch`. Something I noticed is that when I try to use `hit.objectID` for anything, it's never the actual value that's stored in my Meilisearch index or the value returned in the network requests, but instead always a seemingly-random number. Today I traced it down to `adaptGeoResponse` explicitly overwriting the `objectID` field:

https://github.com/meilisearch/meilisearch-js-plugins/blob/bc9b833f743da137817e2270dc8284d9e80ea449/packages/instant-meilisearch/src/adapter/search-response-adapter/geo-reponse-adapter.ts#L7-L16

It seems that this behaviour has been a part of the `geo-response-adapter` since the beginning: https://github.com/meilisearch/meilisearch-js-plugins/commit/ac697077a4cfe1a53ea222d7f1f3c3fd618cecff#diff-b1f517006a5289a6c011e39668cc44e828b73d2056a2ff00cf04e01bc4bfcafcR13

**Expected behavior**
`instant-meilisearch` doesn't change the data I get back from Meilisearch.

**Current behavior**
`instant-meilisearch` changes my `objectID`s to unwanted, useless values. I have to use a workaround of getting the value from `hit._highlightResult.objectID.value`.

**Screenshots or Logs**
image
image

### PR DESCRIPTION
**Pull request by queer**
# Pull Request

## Related issue

Fixes #1308.

## What does this PR do?

This avoids overwriting the `objectID` field if it is already present. This allows code that depends on the `objectID` returned by Meilisearch to function, while still adding it for data sets that don't have it.

This also updates `CONTRIBUTING.md` to have the right command for the geosearch playground.

## PR checklist

Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
hello @queer 

Sorryf for the delay

Can you add tests to ensure the change is well applied?

**Comment by curquiza** [comment]
Also can you run `yarn changeset`? More information in [our CONTRIBUTING steps](https://github.com/meilisearch/meilisearch-js-plugins/blob/main/CONTRIBUTING.md#versioning-with-changesets)

**Comment by flevi29** [comment]
LGTM

**Review by flevi29 — APPROVED** [review]
LGTM

**Review by brunoocasali — APPROVED** [review]
Thanks a lot!

bors merge

**Pull request merged**
