### PR TITLE
Fix `HierarchicalMenu` when `keepZeroFacets` is set to true

### LINKED ISSUE #1040: Facet children are but updated within hierarchical-Menu when using keepZeroFacets
**Description**
I use a hierarchical menu to filter an index based on a facet configuration. To display all categories regardless of the search query, I set `keepZeroFacets` to `true`.

**Current behavior**
The child facets are not displayed when a root facet is selected. If I use a router, select a facet, and then reload the page, the child facets are displayed.

**Expected behavior**
Display of child facets when selecting a facet with children.

**Screenshots or logs**
Not displaying when selecting:
Screenshot 2023-03-22 122429
After site reload when using a HistoryRouter:
Screenshot 2023-03-22 122441

**Environment (please complete the following information):**
- OS:  WSL2 with Debian GNU/Linux 11 (Windows 11 22H2)
- Browser: Mozilla Firefox v111.0 (64-Bit)
- Meilisearch version: v1.0.2
- instant-meilisearch version: v0.11.1
- instantsearch.js version: v4.8.8 (vue-instantsearch)

### PR DESCRIPTION
**Pull request by atoulmet**
# Pull Request

## Related issue
Fixes #1040 

## What does this PR do?
The `initialFacetDistribution` were missing the hierarchical facets we get from the search, which was breaking the `HierarchicalMenu`. 
This PR aims to fix it by adding `fillMissingFacets` function that is called at every search.

It also updates the React playground to `instant-search` v7.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by bidoubiwa — APPROVED** [review]
LGTM 😊

**Review by bidoubiwa — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
