### PR TITLE
Fixed RegExp in filter-adapter.ts and sort-context.ts to work in Safari

### LINKED ISSUE #1277: Sarafi webkit: SyntaxError: Invalid regular expression: invalid group specifier name (js-regexp-lookbehind)
**Description**
`SyntaxError: Invalid regular expression: invalid group specifier name` when loading on Safari Version 15.5 (17613.2.7.1.8).

**Current behavior**
On import of `@meilisearch/instant-meilisearch`, an exception is thrown by older browsers due to RegExp. 

The code in question in `src/adapter/search-request-adapter/filter-adapter.ts`:
```
// Matches first occurrence of an operator
const numericSplitRegExp = /(?<!(?:[<!>]?=|<|>|:).*)([<!>]?=|<|>|:)/
```

Use case is using `searchClient` from `instantMeiliSearch` with `getMeilisearchResults` from `@meilisearch/autocomplete-client`.

The RegExp bug: https://caniuse.com/js-regexp-lookbehind

**Screenshots or Logs**

Stack trace:
```
SyntaxError: Invalid regular expression: invalid group specifier name
RegExp — filter-adapter.ts:33
Module Code — filter-adapter.ts:33
evaluate
moduleEvaluation
moduleEvaluation
moduleEvaluation
moduleEvaluation
moduleEvaluation
(anonymous function)
promiseReactionJob
createInertiaApp.ts:38
```

**Environment (please complete the following information):**
- OS: MacOS
- Browser: Safari Version 15.5 (17613.2.7.1.8)
- Meilisearch version: v1.3.5
- instant-meilisearch version: 0.14.0
- instantsearch.js version: N/A, autocomplete only

### PR DESCRIPTION
**Pull request by papaIOprog**
# Pull Request

## Related issue
Fixes #1277

## What does this PR do?
- Replaces regular expressions that use [lookbehind](https://caniuse.com/js-regexp-lookbehind).
- Resolves a bug specifically affecting Safari.

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @papaIOprog 
Thanks for the PR
Since your PR impacts the library, can you follow the step in the CONTRIBUTING.md regarding changeset?
https://github.com/meilisearch/meilisearch-js-plugins/blob/main/CONTRIBUTING.md#versioning-with-changesets

Also, can you ensure the PR passes the tests? I see some tests in the CI failing.

**Comment by curquiza** [comment]
Also, can you add tests please? 😊

**Comment by papaIOprog** [comment]
I think I created the changeset incorrectly. I'm going to fix this.

**Comment by papaIOprog** [comment]
> Also, can you add tests please? 😊

Did you mean to add tests for these methods?

**Comment by curquiza** [comment]
> Did you mean to add tests for these methods?

Yes please, sorry maybe we already have and you did not have to change them
I'm not an expert in this repo, trying to do my best with the review 😊

**Comment by papaIOprog** [comment]
> > Did you mean to add tests for these methods?
> 
> Yes please, sorry maybe we already have and you did not have to change them I'm not an expert in this repo, trying to do my best with the review 😊

I checked the repository and there are tests for these methods, but I'll add one corner case soon.

**Comment by papaIOprog** [comment]
Here are links to tests that already exist.

For `splitSortString`:
- [split multiple sorting rules](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/sort.test.ts#L54)
- [split one sorting rule](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/sort.test.ts#L66)
- [split no sorting rule](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/sort.test.ts#L72)

For `splitNumericFilter`:
- [split multiple numeric filters](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/filter.test.ts#L194)
- [split equal filter](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/filter.test.ts#L210)
- [split not equal filter](https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/__tests__/filter.test.ts#L226)

**Comment by papaIOprog** [comment]
@curquiza I added 1 test that checks the case when an unusual sorting rule (`_geoPoint`, for example) is not in the first place in the list.

**Comment by papaIOprog** [comment]
@curquiza Hi! I just want to check if everything is ok. Do I need to do anything else?

**Comment by curquiza** [comment]
Sorry @papaIOprog for the delay, working on a lot of things at the same time

@flevi29 if you are around, I would love to have your opinion on this one before reviewing or merging 🙏

**Comment by flevi29** [comment]
I'm pretty sure Babel should be transforming this stuff. Babel is misconfigured.
https://github.com/meilisearch/meilisearch-js-plugins/blob/4d9991e401d8975672f4e75a0975ef21a879a210/packages/instant-meilisearch/.babelrc#L1-L12
It's targeting ... just node? Even at that `current`? That's at minimum `ES2022`. In my opinion it should be targeting the last 2 versions of the more popular browsers (Chrome, Firefox, Edge, Safari), but since `meilisearch-js` at the current moment targets IE11, let's just do that. It looks like this:
https://github.com/meilisearch/meilisearch-js/blob/177947ddaf5b9363152cb3a139b0d4572d7b5ab6/rollup.config.js#L46-L60

@papaIOprog Can you please fiddle with Babel, maybe even update the version that's used, and see if that transforms the RegExp properly? We shouldn't write code for older browsers, we should transform/transpile it for them.

This is not to say that the other changes are bad, I might've not considered every possible combination when I wrote that.

**Comment by papaIOprog** [comment]
@flevi29 Hello! I can test this, but I found that Babel members said that it cannot be polyfilled.
https://github.com/babel/babel/issues/11086#issuecomment-581157679
https://github.com/babel/babel/issues/10699#issuecomment-553411564

**Comment by flevi29** [comment]
Oh, okay, that's unfortunate. Then I don't have any objections to this PR.

**Comment by flevi29** [comment]
It would be nice if Babel at least could warn you about unsupported features, but I can't even find any real discussion about it.
https://stackoverflow.com/questions/76135819/babeljs-does-not-warn-for-unsupported-regex-syntax-with-older-safari-version

We'll just have to wait for people to report these issues :\ .

**Review by curquiza — APPROVED** [review]
thanks @papaIOprog and @flevi29 for your work on this! Really apprecidated

bors merge

**Pull request merged**
